name: Run Create Account Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Kodu indir
      uses: actions/checkout@v3

    - name: Node.js yükle
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Bağımlılıkları yükle
      run: npm install

    - name: Testleri çalıştır
      run: npm test
